// src/app/algorithm/[platform]/[difficulty]/[slug]/page.jsx
import { getAlgorithms } from "@/app/utils";
import { Card, Chip, Divider, Select, Typography } from "@mui/material";
import { getHighlighter } from "shikiji";
import CodeBlock from "@/components/CodeBlock";
import { useTheme } from "@mui/material/styles";
import IconButton from "@mui/material/IconButton";
import { OpenInNew } from "@mui/icons-material";

export async function generateStaticParams() {
  const algorithms = await getAlgorithms();
  let params = [];
  for (const algorithm of algorithms) {
    const path = algorithm.path
      .split(".")
      .slice(0, algorithm.path.split(".").length - 1)
      .join(".");
    const platform = path.split("/")[0];
    const difficulty = path.split("/")[1];
    const slug = path.split("/")[2];
    params.push({
      platform: encodeURIComponent(platform),
      difficulty: encodeURIComponent(difficulty),
      slug: encodeURIComponent(slug),
    });
    params.push({
      platform: platform,
      difficulty: difficulty,
      slug: slug,
    });
  }

  return params;
}

export default async function Page({ params }) {
  const algorithms = await getAlgorithms();
  const platform = decodeURIComponent(params.platform);
  const difficulty = decodeURIComponent(params.difficulty);
  const slug = decodeURIComponent(params.slug);
  const language = algorithms
    .filter((algorithm) => {
      const path = algorithm.path
        .split(".")
        .slice(0, algorithm.path.split(".").length - 1)
        .join(".");
      if (slug.split(".")[1] === undefined)
        return path === `${platform}/${difficulty}/${slug}/${slug}`;
      else
        return (
          path ===
          `${platform}/${difficulty}/${slug}/${slug.split(".")[1].trim()}`
        );
    })
    .map((algorithm) => {
      return algorithm.path
        .split(".")
        [algorithm.path.split(".").length - 1].toLowerCase();
    });

  const languageMap = {
    c: "c",
    cpp: "cpp",
    cc: "cpp",
    py: "python",
    js: "javascript",
    java: "java",
    sql: "sql",
  };

  const paths = language.map((lang) => {
    if (slug.split(".")[1] === undefined)
      return `https://raw.githubusercontent.com/park-jihoo/Algorithm/main/${platform}/${difficulty}/${slug}/${slug}.${lang.toLowerCase()}`;
    else
      return `https://raw.githubusercontent.com/park-jihoo/Algorithm/main/${platform}/${difficulty}/${slug}/${slug.split(".")[1].trim()}.${lang.toLowerCase()}`;
  });

  const highlighter = getHighlighter({
    langs: language.map((lang) => languageMap[lang]),
    themes: ["material-theme-lighter", "material-theme"],
  });

  const codes = await Promise.all(
    paths.map(async (path) => {
      const response = await fetch(path);
      const text = await response.text();
      const lang = path.split(".")[path.split(".").length - 1];
      const light_html = (await highlighter).codeToHtml(text, {
        lang: languageMap[lang],
        theme: "material-theme-lighter",
      });
      const dark_html = (await highlighter).codeToHtml(text, {
        lang: languageMap[lang],
        theme: "material-theme",
      });
      return { light: light_html, dark: dark_html, code: text };
    }),
  );

  return (
    <>
      <Card sx={{ minHeight: "100vh", padding: 2 }}>
        <Chip
          label={platform}
          variant="outlined"
          color="primary"
          sx={{ marginBottom: 1, marginRight: 1 }}
        />
        <Chip
          label={difficulty}
          variant="outlined"
          color="secondary"
          sx={{ marginBottom: 1 }}
        />
        <Typography variant="h4" sx={{ marginBottom: 2 }}>
          {slug}
          <IconButton
            aria-label="link"
            href={
              platform === "leetcode"
                ? `https://leetcode.com/problems/${slug.split("-").slice(1).join("-")}`
                : platform === "프로그래머스"
                  ? `https://programmers.co.kr/learn/courses/30/lessons/${slug.split(".")[0]}`
                  : `https://www.acmicpc.net/problem/${slug.split(".")[0]}`
            }
          >
            <OpenInNew />
          </IconButton>
        </Typography>
        <Divider sx={{ marginBottom: 2 }} />
        <CodeBlock language={language} codes={codes} />
      </Card>
    </>
  );
}

// pages/algorithm/[platform]/[difficulty]/[slug].vue
<script setup>
import Prism from "prismjs";
import "prismjs/components/prism-c.js";
import "prismjs/components/prism-cpp.js";
import "prismjs/components/prism-python.js";
import "prismjs/components/prism-java.js";
import "prismjs/components/prism-sql.js";
import { CodeBlock } from "vue3-code-block";
import { useTheme } from "vuetify";
import { useAlgorithmStore } from "~/stores/algorithm";
import Giscus from "@giscus/vue";

const difficulty = ref("");
const route = useRoute();
const theme = useTheme();

const slug = route.params.slug;
const platform = route.params.platform;
difficulty.value = route.params.difficulty;

const algorithmStore = useAlgorithmStore();

const { data: lang } = await useLazyAsyncData(
  "posts",
  async () => {
    const post = await algorithmStore.getQuestions;
    const langs = post.filter((post) => post.slug === slug)[0].languages;
    const file = platform !== "leetcode" ? slug.split(".")[1].trim() : slug;
    const codes = [];
    for (const l of langs){
      l === "cc" ? l = "cpp" : l;
      const githubUrl = `https://raw.githubusercontent.com/park-jihoo/Algorithm/main/${platform}/${difficulty.value}/${slug}/${file}.${l}`;
      const res = await $fetch(githubUrl);
      codes.push(res);
    }
    return {langs: langs, lang: langs[0], codes: codes};
  },
  { watch: [route] },
);

const getColor = (difficulty) => {
  switch (difficulty) {
    case "Easy":
      return "green";
    case "Medium":
      return "orange";
    case "Hard":
      return "red";
    case "Bronze":
      return "brown";
    case "Silver":
      return "grey";
    case "Gold":
      return "yellow darken-2";
    case "Platinum":
      return "blue darken-2";
    case "lv1":
      return "green";
    case "lv2":
      return "orange";
    case "lv3":
      return "yellow";
    case "lv4":
      return "red";
  }
};

const getLink = (platform, slug) => {
  switch (platform) {
    case "leetcode":
      return `https://leetcode.com/problems/${slug
        .replace(/\d\d\d\d-/g, "")
        .replace(/ /g, "-")}`;
    case "프로그래머스":
      return `https://programmers.co.kr/learn/courses/30/lessons/${slug}`;
    case "백준":
      return `https://www.acmicpc.net/problem/${slug.split(".")[0]}`;
  }
};

useServerSeoMeta({
  ogTitle: () =>
    `${slug.replace(/\d\d\d\d-/g, "").replace(/-/g, " ")} | Algorithm`,
  ogDescription: () =>
    `${platform} - ${difficulty.value} | ${slug
      .replace(/\d\d\d\d-/g, "")
      .replace(/-/g, " ")}`,
  twitterTitle: () =>
    `${slug.replace(/\d\d\d\d-/g, "").replace(/-/g, " ")} | Algorithm`,
});
</script>

<template>
  <div>
    <v-container>
      <v-row justify="center">
        <v-col align-self="auto">
          <v-card outlined class="pa-4 elevation-3">
            <v-card-title class="headline">
              <v-chip class="ml-2" :color="getColor(difficulty)">
                {{ difficulty }}
              </v-chip>
              {{
                route.params.slug.replace(/\d\d\d\d-/g, "").replace(/-/g, " ")
              }}
              <v-btn
                icon
                class="elevation-0"
                rounded="0"
                variant="text"
                :ripple="false"
                :href="getLink(route.params.platform, route.params.slug)"
                target="_blank"
              >
                <v-icon>mdi-open-in-new</v-icon>
              </v-btn>
            </v-card-title>
            <v-card-text>
              <v-select
                v-if="lang.langs"
                v-model:model-value="lang.lang"
                :items="lang.langs"
                label="Select Language"
                outlined
                dense
                color="primary"
                :disabled="lang.langs.length === 1"
              >
              </v-select>
              <template v-if="lang.codes">
                <ClientOnly>
                  <CodeBlock
                    :code="lang.codes[lang.langs.indexOf(lang.lang)]"
                    :prismjs="true"
                    :lang="`${lang.lang === 'cc' ? 'cpp' : lang.lang}`"
                    :theme="`${
                      theme.global.current.value.dark ? 'dark' : 'default'
                    }`"
                    persistent-copy-button
                  />
                </ClientOnly>
              </template>
              <v-skeleton-loader v-else type="paragraph" />
            </v-card-text>
            <Giscus
              id="comments"
              repo="park-jihoo/park-jihoo.github.io"
              repoId="R_kgDOJAfUTw"
              category="General"
              categoryId="DIC_kwDOJAfUT84Cas-2"
              mapping="url"
              strict="1"
              reactionsEnabled="1"
              emitMetadata="0"
              inputPosition="top"
              :theme="`${theme.global.current.value.dark ? 'dark' : 'light'}`"
              lang="ko"
            />
            <v-card-actions>
              <v-spacer></v-spacer>
              <v-btn color="primary">
                <NuxtLink
                  :to="`/algorithm`"
                  style="text-decoration: none; color: inherit"
                >
                  Back to List
                </NuxtLink>
              </v-btn>
            </v-card-actions>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<style>
@use "prismjs/themes/prism-dark.css";
@use "prismjs/themes/prism.css";
</style>
